- js-build/build-doc.js
Hey Frank,
I added the following things to the `build-doc.js` file:
* I pointed out that the all the wrapped methods and constants are made available in a resulting `sodium` object
* I made a short list of the available helper methods
Btw, thanks for your awesome work on making the library even easier to use by fixing the native PRNG issue, the node+browser compliance and the `.mem` file thing :+1: :)
> Better API.md

- js-build/build-wrapper.js
- test/index.html
- test/test.js
Hey Frank,
I'm proposed the following changes:
* `endsWith` on `String` is a proposal for ECMAScript 6, that is not yet a standard or supported everywhere. So I've written an (unfortunately uglier) alternative
* Since you've restored the uppercase parts in constants names, I've updated the html/js test files to match them
> Make it still compatible with ECMAScript 5 & updated constants names

- wrapper/symbols/crypto_generichash_init.json
- wrapper/symbols/crypto_onetimeauth_final.json
- wrapper/symbols/crypto_onetimeauth_init.json
Just noticed that the onetimeauth files I added in #25 had a tab/space indentation inconsistency copied from the equivalent generichash files; fixed both that and the original generichash mistake that I'd copied from.
> Indentation inconsistency

- README.md
When compiling the libsodium.js, uglifyjs is required. Just added this requirement to README.
> Added missing requirement to compilation

- README.md
The README currently instructs one to download the incorrect npm package for [Uglify](https://github.com/mishoo/UglifyJS2). The correct package name is **uglify-js**. The package currently listed does not appear to be legitimate and could be potentially malicious.
> Fix dependency in README

- wrapper/wrap-template.js
> Adding support for big Uint8Arrays in to_string() (that doesn't split buffers arbitrarily)

- README.md
doc.libsodium.org is deprecated or something? All of the links that go there
redirect to a generic homepage. Point these links at their new (stable)
locations.
> README: update links to point to new locations

- bower.json
The `version` property in `bower.json` is deprecated: https://github.com/bower/spec/blob/master/json.md#version
Bower uses [GitHub releases](https://github.com/jedisct1/libsodium.js/releases) (Git tags) to find the correct version.
Libsodium.js provides version 0.4.8 through npm but serves only [0.4.2 as a release tag](https://github.com/jedisct1/libsodium.js/releases/tag/0.4.2). This should be in sync.
> Removed deprecated property "version"

- wrapper/wrap-template.js
libsodium requires proper initialization in order to behave securely (see [core.c#L39](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/core.c#L39)).
libsodium.js should therefore verify that the return value of `_sodium_init()` is zero (e.g. [like sodiumoxide does](https://github.com/dnaq/sodiumoxide/blob/master/src/lib.rs#L68)), and return an error otherwise.
> Add return value check for _sodium_init()

- dist/modules-sumo/libsodium-wrappers-sumo.js
- wrapper/constants.json
- wrapper/symbols/crypto_stream_chacha20_xor.json
- wrapper/symbols/crypto_stream_chacha20_xor_ic.json
I added `crypto_stream_chacha20_xor` and `crypto_stream_chacha20_xor_ic` to the `wrappers`, `symbols` and `libsodium-wrappers-sumo.js`.
As I already mentioned in https://github.com/jedisct1/libsodium.js/issues/73#issuecomment-279680119, I don't have a working `emscripten` setup and would ask you to rebuild the `.min.js` files.
I can also provide a test but I'm not sure I quite understand how your test setup works.
> Add crypto_stream_chacha20_xor

- wrapper/wrap-template.js
Didn't want to conflict with anything you might've been doing for #105 over the last few days @jedisct1, but I just tested locally and everything should work as expected after merging this change and rebuilding with the latest version of my emscripten PR.
My fix was to move up the exports into the `ready` block, so all functions and constants will just be undefined before `ready` is resolved.
> Asynchronous exports

- wrapper/wrap-template.js
> Return entire module as promise

- .gitignore
- Makefile
- README.md
- package.json
This PR will
- remove the need for a global installation of `uglify-es` by adding it to the `devDependencies` and running `npm install` when running `make`.
- fix some typos
- clean up `package.json` (done automatically by npm)
> fix: uglify-es not needed globally + fixed some typos

- wrapper/libsodium-post.js
When running `make`, I get the following error during uglifying:
```
Packing [./dist/modules/libsodium.js]
Parse error at ./dist/modules/libsodium.js:45,7
if typeof(process) === 'object' { process.removeAllListeners("uncaughtExcept
^
ERROR: Unexpected token operator «typeof», expected punc «(»
at JS_Parse_Error.get (eval at <anonymous> (/[redacted]/libsodium.js/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:75:23)
at fatal (/[redacted]/libsodium.js/node_modules/uglify-es/bin/uglifyjs:300:53)
at run (/[redacted]/libsodium.js/node_modules/uglify-es/bin/uglifyjs:239:9)
at Object.<anonymous> (/[redacted]/libsodium.js/node_modules/uglify-es/bin/uglifyjs:169:5)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at …
```
> Fixed syntax error in uglify parsing

- Makefile
$(NODE) is assigned to "nodejs" if existing or "node" otherwise.
This fixes an inconsistency between the argument lists in the sumo-rule: (nodejs with API.md vs. node with API_sumo.md).
> Deduplicate argument lists in makefile

- wrapper/build-wrappers.js
- wrapper/wrap-template.js
This simplifies whitespace handling in the generated wrapper and makes the generated unuglified wrapper .js file better readable and debuggable. This was necessary because VSCode's code folding depends on proper indentation.
> Wrapper readability

- Makefile
- wrapper/build-wrappers.js
- wrapper/symbols/crypto_pwhash_scryptsalsa208sha256_str.json
- wrapper/symbols/crypto_pwhash_str.json
- wrapper/symbols/sodium_version_string.json
- wrapper/wrap-template.js
This is part of the fix for #196.
> Use UTF8String instead of Pointer_stringify

- wrapper/build-doc.js
- wrapper/macros/input_hash_sha256_state_address.js
- wrapper/macros/input_hash_sha512_state_address.js
- wrapper/macros/output_hash_sha256_state.js
- wrapper/macros/output_hash_sha512_state.js
- wrapper/symbols/crypto_hash_sha256_final.json
- wrapper/symbols/crypto_hash_sha256_init.json
- wrapper/symbols/crypto_hash_sha256_update.json
- wrapper/symbols/crypto_hash_sha512_final.json
- wrapper/symbols/crypto_hash_sha512_init.json
- wrapper/symbols/crypto_hash_sha512_update.json
Submitting for review. I wasn't sure if the tests written in `sodium_utils.js` are run with sumo variant, so in the end I didn't add any, but the produced module sumo js seemed to work fine with manual testing.
> Adding wrappers for sha256 and sha512 multipart use case

- wrapper/constants.json
This removes `crypto_secretstream_xchacha20poly1305_NPUBBYTES` as discussed in https://github.com/jedisct1/libsodium.js/issues/226 since it's not used anywhere.
> fix: Remove crypto_secretstream_xchacha20poly1305_NPUBBYTES

- wrapper/symbols/crypto_core_ristretto255_scalar_random.json
I found that the name of the function associated with 'crypto_core_ristretto255_scalar_random' is different.
Please review it.
> fix crypto_core_ristretto255_scalar_random

- wrapper/libsodium-post.js
Building with `NODEJS_CATCH_EXIT=0` and `NODEJS_CATCH_REJECTION=0` tells emscripten to not add the handlers in the first place, so we do not need to compensate after the fact.
Fixes #253
> Let nodejs process handlers be

- wrapper/build-doc.js
- wrapper/macros/input_auth_hmacsha256_state_address.js
- wrapper/macros/input_auth_hmacsha512_state_address.js
- wrapper/macros/output_auth_hmacsha256_state.js
- wrapper/macros/output_auth_hmacsha512_state.js
- wrapper/symbols/crypto_auth_hmacsha256_final.json
- wrapper/symbols/crypto_auth_hmacsha256_init.json
- wrapper/symbols/crypto_auth_hmacsha256_update.json
- wrapper/symbols/crypto_auth_hmacsha512_final.json
- wrapper/symbols/crypto_auth_hmacsha512_init.json
- wrapper/symbols/crypto_auth_hmacsha512_update.json
Submitting for review. Not sure if any tests are required for the `-sumo` module, I can add them if required. I _believe_ I got the state sizes correctly, manual testing appears to show that it works correctly. Here are the calculations I used to calculate the state size:
**crypto_auth_hmacsha256_state**
```
typedef struct crypto_hash_sha256_state {
uint32_t state[8];		// 4 * 8
uint64_t count;		// 8
uint8_t  buf[64];		// 64
} crypto_hash_sha256_state;	// 104
typedef struct crypto_auth_hmacsha256_state {
crypto_hash_sha256_state ictx;	// 4 * 8 + 8 + 64
crypto_hash_sha256_state octx;	// 4 * 8 + 8 + 64
} crypto_auth_hmacsha256_state;		// 208
```
**crypto_auth_hmacsha512_state**
```
typedef struct crypto_hash_sha512_state {
uint64_t state[8];			// 8 * 8
uint64_t count[2];			// 8 * 2
uint8_t …
```
> Add wrappers for crypto_auth_hmacsha(256|512) multipart

- wrapper/symbols/crypto_core_hchacha20.json
I added `crypto_core_hchacha20` to the `wrapper/symbols`.
> Add wrapper for crypto_core_hchacha20

- wrapper/symbols/crypto_core_hsalsa20.json
I copied the 55e6fe130997cc1734917ca69c6f4f4e444ef437 commit that added chacha20 to include salsa20.  Make rebuilds correctly, and I am able to see the crypto_core_hsalsa20 export and use it.  I didn't include the new dist/ files as the linked commit didn't, but I would ask if we could rebuild and bump the npm version of the library to include these changes.
I am also happy to check in my rebuilt changes.
> Add crypto_core_hsalsa20

- package.json
- test/sodium_utils.js
- test/test_helper.js
- wrapper/build-doc.js
- wrapper/macros/input_auth_hmacsha512256_state_address.js
- wrapper/macros/output_auth_hmacsha512256_state.js
- wrapper/symbols/crypto_auth_hmacsha512256.json
- wrapper/symbols/crypto_auth_hmacsha512256_final.json
- wrapper/symbols/crypto_auth_hmacsha512256_init.json
- wrapper/symbols/crypto_auth_hmacsha512256_keygen.json
- wrapper/symbols/crypto_auth_hmacsha512256_update.json
- wrapper/symbols/crypto_auth_hmacsha512256_verify.json
Wanted to compare crypto_auth_hmacsha512256 and keyed crypto_generichash from javascript. So did the following:
- Added wrappers for.crypto_auth_hmacsha512256*
- Added wrapper tests for crypto_auth_hmacsha512256 and crypto_generichash
- Made is easier to test normal vs sumo packages (without errors)
> Added crypto_auth_hmacsha512256 wrappers, new wrapper tests, and made sumo wrapper tests easier to run

- test/sodium.test.ts
For the objects returned by:
```
sodium.crypto_kx_client_session_keys(clientPublic, clientSecret, serverPublic);
sodium.crypto_kx_server_session_keys(serverPublic, serverSecret, clientPublic);
```
The attributes are `sharedTx` and `sharedRx` and not `tx` and `rx`.
> kx-test-fix
